### ISSUE TITLE
does this works?!

### ISSUE THREAD

**Issue by rafaelfaria** [deoxxa/tinder#1]
is this node?

**Comment by deoxxa** [comment]
Whether or not this works depends on what you mean by "works." This did work, as far as what's implemented, when I last checked, but Tinder may have changed in its API since then. If the API has changed, it shouldn't be too much work to bring this library into line with it. Patches welcome! And yes, this is a node library.

For future reference, an issue isn't the best way to ask this kind of thing. I don't really mind, but a lot of people get pretty upset when issues are used for general questions.
